BUTTERFLY-CODE-NEAR/Butterfly_BE

- src/main/java/com/codenear/butterfly/common/domain/BaseEntity.java
> #12 
- Entity 에 공통적으로 정의하는 속성 추가해 편리하게 상속 받아 사용 가능
- 참고 자료
https://dmaolon00.tistory.com/entry/Spring-%EA%B3%B5%ED%86%B5-%ED%95%84%EB%93%9C-%ED%95%98%EB%82%98%EB%A1%9C-%EB%AC%B6%EA%B8%B0-BaseEntity-JpaAuditing
> feat: 공통으로 정의하는 생성, 업데이트 속성 클래스 (#13)

- .gitignore
- src/main/java/com/codenear/butterfly/ButterflyApplication.java
- src/main/java/com/codenear/butterfly/auth/application/AuthService.java
- src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
- src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
- src/main/java/com/codenear/butterfly/member/domain/Member.java
- src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
- src/main/resources/application.properties
> #18 
- 초반에 설정했던, 업데이트 및 추가 날짜 선언해주는 JPA 활성화를 위해 시작 부분에 Auto Jpa 애노테이션 설정
- 좀 더 간편하게 사용하기 위해 @Builder 애노테이션 적용
- FE 측 전달 받은 데이터 기반 회원가입/로그인 
- FE 협업을 위한 Swagger 문서화
- JWT, Security 적용
> 19 회원 가입 및 로그인 로직

- src/main/java/com/codenear/butterfly/auth/application/OauthService.java
- src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
- src/main/java/com/codenear/butterfly/member/application/MemberService.java
- src/main/java/com/codenear/butterfly/member/domain/Member.java
- src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
- src/main/java/com/codenear/butterfly/member/presentation/NicknameController.java
- src/main/java/com/codenear/butterfly/member/presentation/swagger/MemberControllerSwagger.java
- src/main/java/com/codenear/butterfly/member/presentation/swagger/NicknameControllerSwagger.java
- src/main/java/com/codenear/butterfly/point/domain/Point.java
> #108
- Member, Point 분리 작업
- 분리로 인한 회원가입 로직 변경
- 일반, 소셜 회원가입 로직 공통적으로 처리하기 위해 domain 메서드 정의
> 108 refactor member entity point 분리

- src/main/java/com/codenear/butterfly/admin/support/presentation/AdminInquiryController.java
- src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
- src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java
- src/main/java/com/codenear/butterfly/support/domain/InquiryStatus.java
- src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java
- src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterDTO.java
> #112 
- 고객 문의 관련 Entity, Repository, DTO 정의
- 고객 문의 조회, 발송 API 생성
- 관리자 페이지 고객 문의 확인 기능
> 115 고객 문의 관련 도메인 정의

- src/main/java/com/codenear/butterfly/member/application/MemberService.java
- src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
> #197 
- 유저 정보에 [이메일], [쿠폰] 데이터 추가
> feat: 유저 정보 이메일, 쿠폰 추가 (#197)

- src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
- src/main/java/com/codenear/butterfly/consent/domain/Consent.java
- src/main/java/com/codenear/butterfly/consent/domain/ConsentRepository.java
- src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
- src/main/java/com/codenear/butterfly/consent/dto/ConsentInfoResponseDTO.java
- src/main/java/com/codenear/butterfly/consent/dto/ConsentSingleResponseDTO.java
- src/main/java/com/codenear/butterfly/consent/presentation/ConsentController.java
- src/main/java/com/codenear/butterfly/consent/presentation/ConsentControllerSwagger.java
- src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/member/domain/Member.java
> #199 
- 마케팅 수신 동의 목록 반환 API 추가
- 수신 동의 변경 API 추가
> 199 feat 마케팅 수신 동의 변동 및 저장 추가

- src/main/java/com/codenear/butterfly/member/application/MemberService.java
- src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
> #221 
- 유저 정보 반환시, 전화번호 정보가 필요해 추가한다.
> feat: 유저 정보 반환시, 전화번호 추가 (#221)

- src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
- src/main/java/com/codenear/butterfly/member/application/NicknameService.java
- src/main/java/com/codenear/butterfly/member/application/ProfileService.java
- src/main/java/com/codenear/butterfly/member/domain/Member.java
- src/main/java/com/codenear/butterfly/member/domain/dto/ProfileUpdateRequestDTO.java
- src/main/java/com/codenear/butterfly/member/presentation/ProfileController.java
- src/main/java/com/codenear/butterfly/member/presentation/swagger/ProfileControllerSwagger.java
> #220 
- 유저 정보 수정하는 API 초안을 설계했습니다. (닉네임)
- 프로필 이미지 수정 기능을 만들 예정입니다.
> 223 유저 정보 저장 api 생성

- src/main/java/com/codenear/butterfly/address/application/AddressService.java
> #243
- FE측 요청으로 상세 주소 검색 시 데이터가 없을 경우 Null 의 성공 요청 반환을 위해 로직 변경했습니다.
- 기존에 잘못 이해했던 전체의 Null 반환을 Rollback 했습니다.
> refactor(AddressService): 주소 상세 값 반환 변경 (#244)

- src/main/java/com/codenear/butterfly/member/application/MemberService.java
- src/main/java/com/codenear/butterfly/member/application/ProfileService.java
- src/main/java/com/codenear/butterfly/s3/application/S3Service.java
> #290 
- 프로필 이미지가 이미 존재할 경우 교체할 때, 기존의 이미지를 삭제하는 과정의 오류가 발생했습니다. 이를 수정하기 위해 방식을 변경했습니다.
- S3 리팩토링 필요
> 290 fix s3 프로필 이미지 미삭제 버그

- build.gradle
- src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
- src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
- src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
- src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
- src/main/java/com/codenear/butterfly/fcm/application/FCMService.java
- src/main/java/com/codenear/butterfly/fcm/config/FirebaseConfig.java
- src/main/java/com/codenear/butterfly/fcm/domain/FCM.java
- src/main/java/com/codenear/butterfly/fcm/domain/FCMRepository.java
- src/main/java/com/codenear/butterfly/fcm/presentation/FCMController.java
- src/main/java/com/codenear/butterfly/fcm/presentation/FCMControllerSwagger.java
- src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
- src/main/java/com/codenear/butterfly/member/application/MemberFacade.java
> #316 
- 서버에 토큰을 전달해 유저와 매핑해서 보관하는 기능 구현했습니다.
- 토큰 전달로 현재 동의 여부를 파악한 후 Topic 에 저장할 수 있도록 구현했습니다.
> 317 클라이언트 → 서버 토큰 전달 및 저장 기능

- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java
> #325 
- 카카오페이 결제 준비 응답 시 즉시 리다이렉트를 위해 앱 스킴을 반환하였습니다.
> refactor: 카카오페이 결제 준비 응답 시 앱 스킴 반환

- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
> #348 
- 주소와 1대1 관계 매핑했던 것을 주소와 상세주소 컬럼을 추가하여 단순 정보만 저장하게 로직을 수정하였습니다.
> 348 주문 내역 저장 시 주소 저장 방식 변경

- src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java
- src/main/java/com/codenear/butterfly/promotion/domain/Promotion.java
- src/test/java/com/codenear/butterfly/promotion/domain/PointPromotionTest.java
- src/test/java/com/codenear/butterfly/promotion/domain/PromotionTest.java
> #351 
- 프로모션 적용 가능 여부와 두 엔티티를 새로 정의했습니다.
- 프로모션 지급 목록 엔티티와 중복 처리 로직을 구현할 예정입니다.
> 352 프로모션 적용 가능 여부 확인 기능

- src/main/java/com/codenear/butterfly/promotion/domain/Recipient.java
- src/main/java/com/codenear/butterfly/promotion/domain/repository/RecipientRepository.java
- src/test/java/com/codenear/butterfly/promotion/domain/repository/RecipientRepositoryTest.java
> #351 
- 프로모션 참여 목록 테이블 선언 및 중복 지급 확인을 위한 쿼리 메서드 정의
> 354 프로모션 중복 지급 확인 기능

- src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
- src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
- src/main/java/com/codenear/butterfly/global/util/HashMapUtil.java
- src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/CancelPayment.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/CanceledAmount.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/CardInfo.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/KakaoPayRedisField.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/PaymentMethod.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/SinglePayment.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/PickupPaymentRequestDTO.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
- src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java
#399 
- Redis 저장 구조를 Table -> Hash로 변경
- HashMap put 메서드를 사용할 때 value의 값이 null이라면 저장하지 않도록 Overriding
- 객체 생성 방식을 Setter 방식에서 생성자 Builder 방식으로 변경
- 매직넘버 값들을 enum으로 변경
- KakaoPay API 요청 및 Parameter 생성 메서드를 KakaoPaymentUtil로 분리하여 중복 코드 제거
- 카카오페이 테스트 결제 -> 실결제 로 변경
> 399 refactor 카카오 페이 단건결제 코드 리팩토링

- src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
> #402
- PRODUCT_IMAGE("/") 기본 경로에서 -> "product/image"로 변경해 오류 해결했습니다.
- 추후 파일 관리를 용이하게 하기 위해 profileImage 디렉토리도 추가 개선했습니다.
> fix(S3Directory): S3 저장 디렉토리 변경 (#402)

- src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
- src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
- src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
- src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmCountResponseDTO.java
- src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRedisRepository.java
- src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmController.java
- src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmControllerSwagger.java
- src/main/java/com/codenear/butterfly/notify/fcm/application/FCMFacade.java
- src/test/java/com/codenear/butterfly/notify/alarm/application/AlarmServiceTest.java
#404 
- 개인 알림 발송 시 미확인 개인 알림 개수 증가
- 전역 알림 발송 시 미확인 전역 알림 개수 증가
- 미확인 알림 개수 반환 API 개발
- 새로운 상품 추가 알림 발행 시 에러 수정
- 상품 신청 게이지 전송
- 배송 정보 추가
- 카카오페이 실결제 변경
> 404 feat 전체 알림 미확인 알림 개수 기능

- src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
- src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
#411 
- 알림 저장 시 isNew가 항상 false로 저장되어 수정
- 카카오페이 결제 리다이렉트 오류 수정
> 411 fix 알림 저장 시 isnew컬럼 false오류 수정

- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDTO.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
- src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
- src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
- src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java
#419 
- approval, fail, cancel url을 백엔드 api에서 앱으로 변경
- 주문가능 여부 api 구현
- 게이지 수정
- 구간 할인율 설정
- 최대 구매 개수 이상의 물품 구매 시 할인율 차액 포인트백
> 419 fix 카카오페이 결제 오류 수정

- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
#423 
- Redis에 저장이 안되어있고, DB에는 있을 때 재고 없음 오류 발생 수정
- Redis에서 값이 null일 때 DB확인 후 Redis에 저장
- 게이지 및 할인율
> fix(SinglePaymentService): 재고 확인 오류 수정

- src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
#433 
- 결제 성공,취소,실패에 대한 Swagger 가시화
- 포인트백
> docs(SinglePayControllerSwagger): 결제 성공,취소,실패에 대한 Swagger 가시화

- src/main/java/com/codenear/butterfly/promotion/application/PromotionDataAccess.java
- src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java
> #443 
- Redis 캐싱된 PointPromotion 객체의 직렬 /역직렬화 문제 해결
> Fix : Redis 캐싱된 PointPromotion 객체의 직렬 /역직렬화 문제 í해결

- src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
- src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
- src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRedisExpiredKeyListener.java
#445 
- 예약된 재고를 저장하는 redis key를 memberId에서 orderId(unique)로 변경하여 중복 방지
- 상품 이미지 사진 2개 이상으로 처리
> 445 fix 재고 예약 중복 오류 수정

- src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
- src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
- src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
- src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java
#447 
- 결제 (성공,실패,취소) 파라미터 변경
- 결제 이후 앱으로 강제 redirect
- 상품 이미지 사진 2개 이상으로 처리
> 447 fix 카카오페이 결제

- src/main/java/com/codenear/butterfly/notify/fcm/application/FCMTokenService.java
- src/main/java/com/codenear/butterfly/notify/fcm/domain/FCM.java
- src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FCMRepository.java
- src/test/java/com/codenear/butterfly/notify/fcm/application/FCMTokenServiceTest.java
> #458 
- 기존 존재하는 FCM토큰들 삭제 후 재생성
> Refactor : FCM 토큰 생성 방식 수정

- src/main/java/com/codenear/butterfly/payment/tossPay/application/TossPaymentServiceImpl.java
#564 
- TossPaymentService에 @Transactional 추가
- EventListener가 TransactionalEventListener로 받고 있음
- 소상공인 기능 TEST
> 564 fix 토스 페이 결제 시 재고 증감 메세지 발행 오류
