BUTTERFLY-CODE-NEAR/Butterfly_BE

.gitignore
build.gradle
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/resources/application.properties

> #7
- FE 원활한 협업을 위해 Swagger 추가
- 보안을 위한 application-common gitignore 추가

7 feat swagger 설정

---

src/main/java/com/codenear/butterfly/member/domain/Grade.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/Platform.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java

> #12 
- 등급 및 가입 경로는 Enum으로 생성했으며, ERD 기반 Entity 생성 완료
- Todo 작성한 부분 완료해야합니다.
close #15

15 회원 공통 추상 클래스 생성

---

src/main/java/com/codenear/butterfly/common/domain/BaseEntity.java
src/main/java/com/codenear/butterfly/member/domain/Grade.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/Platform.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java

> #13  #15 
- 회원 entity 생성 및 공통으로 정의되는 부분도 정의

12 feat 회원 entity 생성

---

src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java

> #22 #23 
- 스프링 시큐리티에서 정적 파일에 대한 접근 허용 목록 추가

feat: 스프링 시큐리티 설정 화이트리스트 추가 (#23)

---

src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
src/test/java/com/codenear/butterfly/global/property/SecurityPropertiesTest.java

> #22 #25 
- 화이트리스트 변수 추출 및 테스트 코드 추가

25 whitelist 설정 리팩토링 및 테스트코드 추가

---

.gitignore
src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/CustomUserDetailsService.java
src/main/java/com/codenear/butterfly/auth/application/ErrorMessageService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/Role.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java

> #22 #27 
- 이메일 회원가입 로직 구현
- jwt 토큰 설정
- 로그인 기능 구현

27 이메일 회원가입 로직 구현

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java

> #9
- 토큰 생성 및 사용하는 방법은 Member 객체에서 email 및 platform 기반으로 변경

36 토큰 member 객체 email platform 데이터로 생성 변경

---

src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java

> #9 
- 로그인 관련 코드 부분 가독성 향상 및 부분 리팩토링 
- 테스트 코드 및 Swagger 등록

38 로그인 관련 코드 리팩토링 진행 메소드 분할 service 레이어 분리 등

---

src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
src/main/java/com/codenear/butterfly/auth/domain/JwtRefresh.java
src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java

> #41 
- 저장 안되는 버그, 토큰 미삭제 버그 수정

41 fix platform 저장 안되는 오류 및 로그인시 이전 토큰 미삭제 버그

---

src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java

43 swagger api 명세서 작성

---

build.gradle
src/main/resources/application.properties

> #45 #46 
- 헬스 체크를 위한 actuator 엔드포인트 추가

feat: 헬스 체크를 위한 actuator 엔드포인트 추가

---

.gitignore
Jenkinsfile

chore: Jenkins 파일 설정

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java

refactor: 플랫폼 검증 로직 리팩토링

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java

refactor: 서비스 계층에서 로그 처리

---

build.gradle
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/global/exception/ValidationExceptionHandler.java

56 refactor request dto 검증 로직 추가

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/auth/exception/AuthExceptionHandler.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java

> #55
- ControllerAdvice와 ExceptionHandler를 이용한 중복된 try catch 제거

55 refactor 중복 try catch 제거

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/email/CustomUserDetailsService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
src/main/java/com/codenear/butterfly/auth/exception/AuthExceptionHandler.java
src/main/java/com/codenear/butterfly/auth/exception/message/MessageUtil.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/test/java/com/codenear/butterfly/auth/application/CustomUserDetailsServiceTest.java

refactor: 메시지 처리 클래스 패키지 변경

---

src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRequestDTO.java
src/main/java/com/codenear/butterfly/auth/validator/PasswordValidator.java
src/main/java/com/codenear/butterfly/auth/validator/ValidPassword.java
src/main/java/com/codenear/butterfly/global/exception/ValidationExceptionHandler.java
src/main/java/com/codenear/butterfly/member/domain/Platform.java

> #61 
-회원 가입, 로그인 부분에 비밀번호, 플랫폼, 닉네임 검증 추가

61 feat 회원 가입 및 로그인 검증 부분 추가

---

.gitignore
build.gradle
src/main/java/com/codenear/butterfly/global/config/QuerydslConfig.java
src/main/java/com/codenear/butterfly/member/application/NicknameService.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepositoryCustom.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepositoryImpl.java
src/main/java/com/codenear/butterfly/member/presentation/NicknameApi.java
src/main/java/com/codenear/butterfly/member/util/KoreanCharacterRegex.java

> #63 
- 닉네임 2글자 + 숫자 랜덤 생성 로직 추가

63 feat 닉네임 생성 api

---

src/main/java/com/codenear/butterfly/auth/jwt/JwtUtil.java
src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java
src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java

> #74 
- jwt 코드 전체적 리팩토링 진행 및 성능 향상, 에러 처리
- 리프레쉬 토큰 에러 처리 템플릿 적용

74 refactor jwt 코드 리팩토링 및 성능 향상 에러 처리

---

src/main/java/com/codenear/butterfly/auth/exception/AuthException.java
src/main/java/com/codenear/butterfly/global/exception/BusinessBaseException.java
src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java

> #77
- 비즈니스 공통 런타임 정의 및 글로벌 에러 처리 등록
- 토큰 에러 처리 부분 글로벌 처리로 변경

77 feat 비즈니스 공통 클래스 정의

---

src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java

> #79 
- auth 도메인 인증 처리 부분 리팩토링 진행

79 refactor auth 도메인 인증 처리 변환

---

src/main/java/com/codenear/butterfly/auth/jwt/CookieUtil.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthControllerSwagger.java
src/main/java/com/codenear/butterfly/test/TestController.java

> #81 
- 쿠키 null 값 에러 처리 추가
- auth 컨트롤러 및 swagger 리팩토링
- Test 컨트롤러 생성

81 refactor 쿠키 null 에러 처리 및 auth 컨트롤러 리팩토링

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/application/jwt/JwtService.java
src/main/java/com/codenear/butterfly/auth/application/jwt/TokenValidator.java
src/main/java/com/codenear/butterfly/auth/presentation/JwtFilter.java
src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
src/main/java/com/codenear/butterfly/auth/util/CookieUtil.java
src/main/java/com/codenear/butterfly/auth/util/JwtUtil.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java

86 refactor 소셜 로그인 일반 로그인 초기 분리

---

src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/OauthDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
src/main/java/com/codenear/butterfly/global/util/ResponseUtil.java
src/main/java/com/codenear/butterfly/member/domain/repository/MemberRepository.java

> #88 
- 소셜 로그인 파트 분리 작업을 진행했다.

88 refactor 소셜 로그인 파트 분리 작업

---

src/main/java/com/codenear/butterfly/auth/domain/dto/OauthDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
src/main/java/com/codenear/butterfly/auth/presentation/OauthControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java

> #91 
- 컨트롤러에 Swagger 적용 및 리팩토링

91 feat refactor oauth 컨트롤러 swagger 적용

---

src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java

> ex) #93 
- Global 예외 핸들러 체크, 언체크 예외 추가

refactor: Global 예외 핸들러에 체크, 언체크 예외 추가 (#93)

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/JwtService.java
src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/application/validator/TokenValidator.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/OauthController.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/OauthControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java

> #95 
- 유지보수를 위해 파일을 알맞는 계층으로 이동 작업을 했다.

95 refactor 유지보수를 계층에 알맞는 파일 이동

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthLoginDTO.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java
src/main/java/com/codenear/butterfly/auth/validator/PasswordValidator.java

97 refactor 개인 소셜 dto 분리 작업

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthLoginDTO.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java

> #100 
- 개인 로그인 및 회원가입 DTO 재정의
- Swagger에 로그인, 회원가입 오류 코드 추가

100 refactor 개인 로그인 회원가입 swagger 수정

---

src/main/java/com/codenear/butterfly/auth/annotation/PasswordValidator.java
src/main/java/com/codenear/butterfly/auth/annotation/ValidPassword.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java

> #99 
- 커스텀 비밀번호 검증 어노테이션 수정을 했다. 또한, 긴급 fix 하는 부분도 함께 적용

99 refactor 커스텀 비밀번호 검증 어노테이션 수정

---

src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
src/main/java/com/codenear/butterfly/member/presentation/MemberControllerSwagger.java

> #105 
- 메인 / 마이페이지 유저 정보 API 추가
- 유저 Repository 반환 값 및 Swagger 명세서 변경

105 feat 메인 마이페이지 유저 정보 api 추가

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
src/main/java/com/codenear/butterfly/product/exception/ProductException.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

> #107 
- 상품 정보를 호출하는 REST Api 생성
- 할인률 데이터 포맷 정수부 3자리 소수부 2자리로 하였음(논의 필요)
- 상품이 없을 경우 404 에러 처리

107 feat 메인 카테고리 상품 정보 api 추가

---

build.gradle
src/main/resources/templates/admin/support/inquiryList.html
src/main/resources/templates/admin/support/inquiryModal.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/index.html

> #112
- 고객 문의 등록 후 관리할 관리자 페이지 생성
- 관리자 페이지 도메인 및 컨트롤러 생성

113 고객 문의 관리자 페이지 생성

---

src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java

> #112 
- 고객 문의 조회, 발송 API 생성
- Swagger API 문서화 생성

117 고객 문의 조회 발송 rest api 생성

---

src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/application/NicknameService.java
src/main/java/com/codenear/butterfly/member/domain/Grade.java

> #121 
- (FE 요청) 유저 등급 정보 Int 타입으로 변경

121 refactor 유저 정보 등급 int 변경

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java
src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterDTO.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryControllerSwagger.java

refactor: 고객 문의 API Swagger 문서 작성 (#123)

---

build.gradle
src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
src/main/java/com/codenear/butterfly/search/application/SearchService.java
src/main/java/com/codenear/butterfly/search/presentation/SearchController.java

> #126 
- 최근 검색어 추가 및 조회 기능 설계

127 최근 검색어 추가 및 조회 기능

---

src/main/java/com/codenear/butterfly/search/presentation/SearchController.java

feat: 최근 검색어 삭제 기능 API 추가 (#129)

---

src/main/java/com/codenear/butterfly/product/application/CategoryService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Category.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java
src/main/java/com/codenear/butterfly/product/util/CategoryConverter.java

111 feat 카테고리 별 상품 조회 api 추가

---

src/main/java/com/codenear/butterfly/product/application/KeywordService.java
src/main/java/com/codenear/butterfly/product/domain/Keyword.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRepository.java
src/main/java/com/codenear/butterfly/search/application/SearchService.java
src/main/java/com/codenear/butterfly/search/presentation/SearchController.java

> #126 
- 연관 검색어 기능 생성
- API 명세서 생성

131 연관 검색어 기능 추가

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/presentation/AuthController.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/AuthControllerSwagger.java

> #137 
- 회원가입 로직에 JWT 토큰 발급 추가

회원가입 로직에 JWT 토큰 발급 추가 (#137)

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java

135 api 명세서 추가

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java

> #140 
- SwaggerConfig 최적화를 진행

SwaggerConfig 최적화 (#140)

---

src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/domain/dto/InquiryListDTO.java

고객 문의 리스트 날짜 추가 (#142)

---

src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

> #134 
- 전체 카테고리 및 일반 카테고리 api 분리

feat: 전체 카테고리 및 일반 카테고리 api 분리

---

src/main/java/com/codenear/butterfly/search/application/SearchService.java
src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java

검색어 부분 삭제 추가 (#145)

---

src/main/java/com/codenear/butterfly/search/application/SearchService.java

> #126 
- 검색어 정렬 최근 거 우선 순위로 변경을 위해서 Set -> List로 변경했음. 또한, 중복 체크를 Set 에서는 가능했지만 List 변경을 불가능 했기 때문에 새로 등록함.

검색어 정렬 최근 거 우선 순위 변경 (#147)

---

src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java

> #112 
- 고객 문의 리스트 날짜 최신 순으로 반환으로 변경

고객 문의 리스트 최신 날짜 우선 순위 반환 (#150)

---

src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Option.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

> #144 
- 상품 상세 rest api 개발
- 상품 설명, 옵션, 수량 추가
- 상품 상세 api 호출 예시

144 상품 상세 rest api 개발

---

src/main/java/com/codenear/butterfly/auth/domain/dto/CustomUserDetails.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
src/main/java/com/codenear/butterfly/member/domain/repository/nickname/ForbiddenWordRepository.java
src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Favorite.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/domain/repository/FavoriteRepository.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

> #153 
- 찜 목록 추가, 삭제, 조회
- 해당 상품 좋아요 여부
- 상품 정보 Api Swagger

153 찜 목록 기능 추가

---

src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthLoginDTO.java

> #155 
- CustomUserDetails 미사용
- Member 객체 직접 사용
- 로그인 시 플랫폼 포함

refactor: 요청 시 플랫폼 포힘하게끔 로직 수정

---

src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/domain/dto/MemberDTO.java
src/main/java/com/codenear/butterfly/member/presentation/MemberController.java
src/main/java/com/codenear/butterfly/member/presentation/swagger/MemberControllerSwagger.java
src/main/java/com/codenear/butterfly/point/application/PointService.java
src/main/java/com/codenear/butterfly/point/domain/PointRepository.java

> #161 
- 시큐리티 권한 부분을 사용자 객체 저장으로 완전 변경

162 스프링 시큐리티 사용자 정보 저장 방식 변경

---

src/main/java/com/codenear/butterfly/ButterflyApplication.java
src/main/java/com/codenear/butterfly/global/config/RedisConfig.java

feat: Redis 설정 추가 (#164)

---

src/main/java/com/codenear/butterfly/search/application/SearchService.java
src/main/java/com/codenear/butterfly/search/presentation/SearchController.java
src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java

refactor: 검색 API 새로운 객체로 리팩토링 (#166)

---

src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java
src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/domain/InquiryRepository.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryControllerSwagger.java

> #161 
- 고객 문의 API 새로운 객체로 리팩토링

168 고객 문의 api 새로운 객체로 리팩토링

---

src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

refactor: 상품 Api 새로운 객체로 리팩토링

---

src/main/java/com/codenear/butterfly/auth/application/email/EmailLoginService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java

> #172
- code near 로그인&회원가입 리팩토링

172 code near 로그인회원가입 리팩토링

---

src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java

> #174 
- 상품 최대 구매 갯수 대문자 표기 핫픽스

fix: 상품 최대 구매 갯수 대문자 표기 핫픽스

---

src/main/java/com/codenear/butterfly/search/presentation/SearchControllerSwagger.java

fix: 파라미터 변경 및 인터페이스 안쓰는 부분 정리 (#184)

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/Address.java
src/main/java/com/codenear/butterfly/address/domain/AddressRepository.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressCreateDTO.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressUpdateDTO.java
src/main/java/com/codenear/butterfly/address/exception/AddressException.java
src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/member/domain/Member.java

> #176, #177 
- 주소 [추가] [조회] [수정] 기능 추가 및 주소 요소들 정의

177 주소 추가, 조회, 수정 기능

---

src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Option.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/product/presentation/ProductControllerSwagger.java

> #188 
- 찜 목록 상품 반환 api 리팩토링
- 옵션에 컬럼 추가

188 refactor 찜 목록 상품 반환 api 리팩토링

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java

187 주소 상세 보기 기능

---

src/main/java/com/codenear/butterfly/product/application/FavoriteService.java

> #188 
- 찜 목록에서 상품 반환 -> 상품 DTO 반환

refactor: 찜 목록 DTO 반환

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/Address.java
src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java

> #176 
- 메인 주소 변경 기능 추가
- 주소 삭제 기능

191 메인 주소 변경 기능

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java

> #176 
- 주소 삭제 기능 추가 (메인 주소 삭제할 경우, 마지막 주소가 메인으로 변경되는 로직 구성)
- 메서드 모듈화 리팩토링 진행

194 주소 삭제 기능

---

src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java

refactor: 수신 동의 명칭 변경 (#203)

---

src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/CardInfo.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderType.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/PaymentRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java

> #200 
- Redis에 주문 유형 및 주소 Id 임시 저장 로직 추가
- 결제 승인 시 주문 내역 저장

200 상품 구매 요청 dto 수정

---

src/main/java/com/codenear/butterfly/auth/domain/JwtRefreshRepository.java
src/main/java/com/codenear/butterfly/auth/presentation/CustomLogoutHandler.java
src/main/java/com/codenear/butterfly/auth/presentation/CustomLogoutSuccessHandler.java
src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/filter/JwtFilter.java

> #204 
- 로그아웃 기능 추가 완료
- API 명세서 어떤 방식으로 추가할지 고민

207 로그아웃 기능 추가

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayControllerSwagger.java

> #212 
- 결제 승인 시 ResponseDTO 반환

refactor: 결제 승인 시 ResponseDTO 반환

---

src/main/java/com/codenear/butterfly/auth/presentation/LogoutController.java
src/main/java/com/codenear/butterfly/auth/presentation/swagger/LogoutControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java

214 로그아웃 api 명세서

---

src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/auth/domain/dto/AuthRegisterDTO.java
src/main/java/com/codenear/butterfly/consent/application/ConsentService.java

> #216 
- CODE NEAR 회원가입 시 마케팅 동의 추가

216 feat code near 플랫폼 회원가입 시 마케팅 동의 추가

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java

> #176 #218 
- FE 요청으로 전송 데이터에 메인 주소 여부 추가

feat: 메인 주소 여부 전송 데이터 추가 (#218)

---

build.gradle
src/main/java/com/codenear/butterfly/s3/application/S3Service.java
src/main/java/com/codenear/butterfly/s3/config/S3Config.java
src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
src/main/java/com/codenear/butterfly/s3/exception/S3Exception.java

> #220 
- S3 연결 Cofing과 삭제 기능을 구현했습니다.

227 s3 config 설정 파일 삭제 기능 구현

---

src/main/java/com/codenear/butterfly/s3/application/S3Service.java
src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
src/test/java/com/codenear/butterfly/s3/application/S3ServiceTest.java

229 s3 파일 등록 기능 구현

---

src/main/java/com/codenear/butterfly/member/application/ProfileService.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/dto/ProfileUpdateRequestDTO.java
src/main/java/com/codenear/butterfly/member/presentation/ProfileController.java
src/main/java/com/codenear/butterfly/member/presentation/swagger/ProfileControllerSwagger.java
src/main/java/com/codenear/butterfly/s3/application/S3Service.java

> #220 
- S3 연동 후, 프로필 사진 변경을 위해 정보를 추가했습니다.

225 사진 저장 기능 도입 후 정보 저장 추가

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressAddResponseDTO.java
src/main/java/com/codenear/butterfly/address/presentation/AddressController.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java

232 fix 주소 기능 관련 반환 데이터 수정

---

build.gradle
src/main/java/com/codenear/butterfly/sms/application/SmsService.java
src/main/java/com/codenear/butterfly/sms/application/SmsServiceImpl.java
src/main/java/com/codenear/butterfly/sms/config/SmsConfig.java
src/test/java/com/codenear/butterfly/sms/application/SmsServiceTest.java

> #220 
- SMS 메시지 전송 기능을 구현했습니다.
- 랜덤 6자리 생성
- Redis에 인증 번호 보관

234 sms 기능

---

src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/CancelPayment.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/CanceledAmount.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/ApproveRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/CancelRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/CancelResponseDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/CancelPaymentRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/SinglePayControllerSwagger.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/cancelPayment/CancelPaymentControllerSwagger.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java

> #226 
- 결제 완료된 건에 대한 결제 취소 로직 추가
- 결제 취소에 대한 데이터 데이터베이스에 저장

226 상품 결제 취소

---

src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
src/main/java/com/codenear/butterfly/certify/application/CertifyValidator.java
src/main/java/com/codenear/butterfly/certify/dto/CertifyRequestDTO.java
src/main/java/com/codenear/butterfly/certify/presentation/CertifyController.java
src/main/java/com/codenear/butterfly/certify/presentation/CertifyControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/global/util/RandomUtil.java
src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/test/java/com/codenear/butterfly/global/util/RandomUtilTest.java
src/test/java/com/codenear/butterfly/sms/application/SmsServiceTest.java

> #220 
- 랜덤 6자리 생성 기능 및 휴대폰 인증 기능 구현했습니다.

237 랜덤 6자리 생성 후 redis 저장 기능

---

src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/application/NicknameService.java
src/main/java/com/codenear/butterfly/member/application/ProfileService.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java

> #240 
- 프로필 수정 로직 버그를 찾아내 수정 완료 했습니다.

241 프로필 수정 로직 수정

---

src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
src/main/java/com/codenear/butterfly/certify/domain/CertifyMessage.java
src/main/java/com/codenear/butterfly/certify/domain/dto/CertifyRequestDTO.java
src/main/java/com/codenear/butterfly/certify/presentation/CertifyController.java
src/main/java/com/codenear/butterfly/certify/presentation/CertifyControllerSwagger.java

> #246 
- 휴대폰 인증 문자 템플릿을 적용했습니다.

246 refactor 휴대폰 인증 문자 내용 변경

---

src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java

> #238 
- 결제 성공, 실패, 취소 swagger에서 숨김 처리
- 결제 상태를 반환하는 로직 추가

238 상품 결제 완료 시 결과 반환 로직 리팩토링

---

src/main/java/com/codenear/butterfly/kakaoPay/application/OrderDetailsService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/BasePaymentRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDetailsDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java

249 주문 내역 조회 api

---

src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ReadyResponseDTO.java

> #253 
- 카카오페이 모바일 다이렉트 링크 추가

refactor: 카카오페이 모바일 다이렉트 링크 추가

---

src/main/java/com/codenear/butterfly/admin/AdminController.java
src/main/java/com/codenear/butterfly/admin/member/application/AdminMemberService.java
src/main/java/com/codenear/butterfly/admin/member/presentation/AdminMemberController.java
src/main/resources/templates/admin/member/member.html
src/main/resources/templates/adminDashboard.html
src/main/resources/templates/fragments/scripts.html
src/main/resources/templates/fragments/sidebar.html

> #251 
- 회원 admin 페이지 생성했습니다.

259 회원 admin 페이지 생성

---

src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java

> #266 
- 상품 테이블 subtitle -> companyName으로 컬럼명 변경

refactor: 상품 테이블 subtitle -> companyName으로 컬럼명 변경

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/Address.java
src/main/java/com/codenear/butterfly/geocoding/application/GeocodingClient.java
src/main/java/com/codenear/butterfly/geocoding/application/GeocodingService.java
src/main/java/com/codenear/butterfly/geocoding/application/GeocodingValidator.java
src/main/java/com/codenear/butterfly/geocoding/exception/ErrorMessage.java
src/test/java/com/codenear/butterfly/geocoding/application/GeocodingClientTest.java
src/test/java/com/codenear/butterfly/geocoding/application/GeocodingServiceTest.java

> #268 
- 거리 계산 로직 추가해, 저장하는 기능을 구현했다.

269 geocoding 거리 계산 로직 추가

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java

> #271 
- 결제 완료 시 리다이렉트 url 변경

refactor: 결제 완료 시 리다이렉트 url 변경

---

src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderStatus.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/order/OrderDetailsDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java

> #273 
- 주문 상태 enum 클래스 생성 후 리팩토링
- string -> enum

273 refactor 주문 상태 리팩토링

---

src/main/java/com/codenear/butterfly/support/domain/FAQ.java

- BaseEntity 로 생성일 및 수정일 구분하기 위해 추가했습니다.
> #275 
- FAQ 관련 DB를 생성했습니다.

feat(FAQ): FAQ 관련 DB 생성 (#276)

---

src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/OrderStatus.java

> #279 
- 주문 상태에 주문 취소 status 추가

279 feat 주문 상태에 주문 취소 status 추가

---

src/main/java/com/codenear/butterfly/admin/exception/AdminException.java
src/main/java/com/codenear/butterfly/admin/support/application/FAQService.java
src/main/java/com/codenear/butterfly/admin/support/domain/dto/FAQRequest.java
src/main/java/com/codenear/butterfly/support/domain/FAQ.java
src/main/java/com/codenear/butterfly/support/domain/FAQRepository.java
src/test/java/com/codenear/butterfly/admin/support/application/FAQServiceTest.java

> #275 
- 질문 및 답변 등록 테스트 코드와 비즈니스 기능을 구현했습니다.

278 질문 및 답변 등록 admin

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/DiscountRate.java
src/main/java/com/codenear/butterfly/product/domain/Option.java
src/main/java/com/codenear/butterfly/product/domain/Price.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java

> #287 
- 상품 서비스 리팩토링
- 상품 DTO 변환 Mapper 클래스 추가
- 상품 신청 인원에 따른 할인률 적용
- 구간 별 할인률을 설정하는 엔티티 추가

287 feat 상품 신청 인원에 따른 할인률 적용

---

build.gradle
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/global/exception/GlobalExceptionHandler.java
src/main/java/com/codenear/butterfly/member/application/ProfileService.java
src/main/java/com/codenear/butterfly/member/util/CustomMultipartFile.java
src/main/java/com/codenear/butterfly/member/util/ImageResizeUtil.java
src/main/resources/application.properties

> #286 
- 이미지 업로드 리사이징 기능을 추가했습니다.

286 feat s3 이미지 업로드 리사이징

---

src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java

> #291 
- 상품 목록 조회 api에 품절 여부를 추가하였습니다.

feat: 상품 목록 조회 api에 품절 여부 추가

---

src/main/java/com/codenear/butterfly/kakaoPay/application/OrderDetailsService.java

feat(OrderDetailsService): 주문 내역 최신순 정렬(#296)

---

src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiresResponse.java
src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryDetailsResponse.java
src/main/java/com/codenear/butterfly/global/exception/ErrorMessage.java
src/main/java/com/codenear/butterfly/support/application/InquiryFacade.java
src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/exception/SupportException.java

> #297 
- 질문 목록 리스트 반환 기능 구현했습니다. 등록 날짜 정렬은 기존에도 정렬이 생성 기준이라 바로 적용했습니다.

298 질문 목록 리스트 등록 날짜 정렬

---

src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryDetailsResponse.java
src/main/java/com/codenear/butterfly/global/exception/ErrorMessage.java
src/main/java/com/codenear/butterfly/support/application/InquiryFacade.java
src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/exception/SupportException.java

> #297 
- 질문 상세 보기 기능을 추가했습니다. 또한, Facade 패턴을 도입해 책임을 분할하고 참조 형식을 변경했습니다.

299 상세보기 기능

---

src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
src/main/java/com/codenear/butterfly/admin/support/domain/dto/InquiryAnswerRequest.java
src/main/java/com/codenear/butterfly/support/domain/Inquiry.java

> #297 
- 상태 및 답변 변경할 수 있는 기능과 답변을 삭제할 수 있도록 기능을 추가했습니다.

302 상태 및 답변 변경 기능과 삭제 기능 추가

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/resources/templates/admin/products/product-edit.html
src/main/resources/templates/admin/products/product-list.html

> #295 
- 상품 관리 페이지 화면을 추가하였습니다.
- 상품 업데이트 로직을 구현하였습니다.
- 상품 삭제 로직을 구현하였습니다.

295 상품 관리자 페이지 화면 구성

---

src/main/java/com/codenear/butterfly/support/application/InquiryService.java
src/main/java/com/codenear/butterfly/support/domain/Inquiry.java
src/main/java/com/codenear/butterfly/support/domain/dto/InquiryRegisterRequest.java
src/main/java/com/codenear/butterfly/support/presentation/InquiryController.java
src/main/java/com/codenear/butterfly/support/presentation/swagger/InquiryControllerSwagger.java

> #308 
- 질문 생성 과정에 기본 메시지 로직을 수정했습니다. 또한, 가독성 향상을 위한 리팩토링도 진행했습니다.

308 refactor 질문 생성 과정 기본 메시지 로직 수정

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java

> #310 
- redirect URL butterfly 스킴 적용

refactor: redirect URL butterfly 스킴 적용

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java

> #313 
- 불필요 response 파라미터 제거

fix: 불필요 파라미터 제거

---

build.gradle
src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
src/main/java/com/codenear/butterfly/fcm/application/FCMService.java
src/main/java/com/codenear/butterfly/fcm/application/FirebaseMessagingClient.java
src/main/java/com/codenear/butterfly/fcm/config/FirebaseConfig.java
src/main/java/com/codenear/butterfly/fcm/domain/FCM.java
src/main/java/com/codenear/butterfly/fcm/domain/FCMRepository.java
src/main/java/com/codenear/butterfly/fcm/exception/FCMException.java
src/main/java/com/codenear/butterfly/fcm/presentation/FCMController.java
src/main/java/com/codenear/butterfly/fcm/presentation/FCMControllerSwagger.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/member/application/MemberFacade.java

> #316 
- memberId 기준 푸시 알림을 할 수 있는 기능 구현

319 member id 기준 푸시 알람 기능

---

src/main/java/com/codenear/butterfly/address/application/AddressService.java
src/main/java/com/codenear/butterfly/address/domain/Address.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponse.java
src/main/java/com/codenear/butterfly/address/domain/dto/AddressResponseDTO.java
src/main/java/com/codenear/butterfly/address/presentation/AddressControllerSwagger.java

> #321 
- 주소 기능에 배달비를 추가해 반환하도록 변환했습니다.

321 feat 주소 배달비 추가

---

.gitignore
src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/dto/DiscountRateRequest.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductEditResponse.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
src/main/java/com/codenear/butterfly/product/domain/DiscountRate.java
src/main/java/com/codenear/butterfly/product/domain/Keyword.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRepository.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html
src/main/resources/templates/admin/products/product-list.html

> ex) #이슈번호, #이슈번호
- 관리자 페이지 상품 추가 기능을 구현하였습니다.
- 상품 수정 시 추가 할인율 설정을 가능하게 하였습니다.

323 상품 추가 페이지

---

src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
src/main/java/com/codenear/butterfly/fcm/application/FCMService.java
src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java
src/main/java/com/codenear/butterfly/fcm/presentation/FCMController.java
src/test/java/com/codenear/butterfly/fcm/application/FirebaseMessagingClientTest.java

327 특정 topic 푸시 알람 기능

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
src/main/java/com/codenear/butterfly/admin/support/application/InquiryAdminService.java
src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
src/main/resources/templates/admin/products/product-list.html

> #332 
- 버튼형 신상품 알림 기능을 추가했습니다.

332 feat 신상품 알림 추가

---

src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
src/main/java/com/codenear/butterfly/consent/domain/Consent.java
src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
src/main/java/com/codenear/butterfly/fcm/application/FCMFacade.java
src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java

> #316 
- 기존 동의 사항 변경시 토픽 변동 기능을 적용했습니다.

334 기존 동의 사항 변경될 시 토픽 변동 기능

---

src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
src/test/java/com/codenear/butterfly/fcm/application/FCMMessageServiceTest.java

> #316 
- 동의 여부에 따라 전송 기능 추가했습니다.

337 동의 여부에 따라 전송 기능

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/product/domain/Product.java

> #335 
- 상품 주문 완료 시 참여율 재고 변화 로직을 추가하였습니다

335 상품 주문 완료 시 참여율 재고 변화

---

src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/consent/application/ConsentDataAccess.java
src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
src/main/java/com/codenear/butterfly/consent/application/ConsentUpdateService.java
src/main/java/com/codenear/butterfly/consent/domain/Consent.java
src/main/java/com/codenear/butterfly/consent/dto/ConsentUpdateRequest.java
src/main/java/com/codenear/butterfly/consent/presentation/ConsentController.java
src/main/java/com/codenear/butterfly/consent/presentation/ConsentControllerSwagger.java
src/main/java/com/codenear/butterfly/fcm/application/FCMMessageService.java
src/main/java/com/codenear/butterfly/fcm/application/FCMTokenService.java
src/test/java/com/codenear/butterfly/fcm/application/FCMMessageServiceTest.java

> #340 
- 순환 참조 문제를 해결하기 위해 클래스, 메소드 분리 및 각종 리팩토링을 적용했습니다.

340 fix 순환 참조 문제

---

src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
src/main/java/com/codenear/butterfly/certify/application/CertifyValidator.java
src/main/java/com/codenear/butterfly/certify/exception/CertifyException.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java

> #342 
- 전화 번호 중복 에러 처리 추가했습니다.

342 fix 중복 전화 번호 에러 처리

---

src/main/java/com/codenear/butterfly/product/domain/Product.java

refactor: 상품 도메인 수정 메서드 리팩토링

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/s3/domain/S3Directory.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html

> #350 
- 상품 추가 및 수정 시 S3에 이미지 업로드/수정 로직을 구현하였습니다.

350 상품 사진 수정 로직

---

src/main/java/com/codenear/butterfly/fcm/domain/FCMMessageConstant.java
src/main/java/com/codenear/butterfly/point/domain/Point.java
src/main/java/com/codenear/butterfly/promotion/application/CitationPromotionService.java
src/main/java/com/codenear/butterfly/promotion/application/PromotionDataAccess.java
src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java
src/main/java/com/codenear/butterfly/promotion/domain/repository/PointPromotionRepository.java
src/main/java/com/codenear/butterfly/promotion/exception/PromotionException.java
src/test/java/com/codenear/butterfly/promotion/application/CitationPromotionServiceTest.java
src/test/java/com/codenear/butterfly/promotion/domain/PointPromotionTest.java

> #351 
- 프로모션 최종 비즈니스 로직 설계를 완료했습니다. 
- 휴대폰 인증 로직을 재사용에 용이하게 변경하고, Controller 위치를 변경할 예정입니다.

357 프로모션 최종 비즈니즈 기능

---

src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/point/domain/PointRepository.java
src/main/java/com/codenear/butterfly/product/domain/Price.java
src/main/java/com/codenear/butterfly/product/domain/Product.java

> #355 
- 여러 개의 상품 구입 시에 추가 할인율이 변동되면 포인트를 반환해주는 프로모션을 적용하였습니다.

355 상품 구입 후 추가 할인율 변동 시 포인트 반환

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html

> #364 
- 개별 내용물의 용량(중량)과 소비기한 컬럼을 추가하였습니다.

364 refactor 상품 컬럼 추가

---

src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java

> #366 
- 상품 sold out시 하단 정렬하는 로직을 추가하였습니다.

366 feat 상품 sold out시 하단 정렬

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/product/domain/Favorite.java
src/main/java/com/codenear/butterfly/product/domain/repository/FavoriteRepository.java

> #369 
- 찜 목록에 삭제하려는 상품이 담겨있을 시 관리자 페이지에서 상품이 삭제되지 않는 오류를 해결하였습니다.

369 fix 상품 삭제 불가 오류

---

src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmResponse.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmsResponse.java
src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java
src/test/java/com/codenear/butterfly/notify/alarm/application/AlarmServiceTest.java

> #371 
- 알림 목록 API 반환 구현 완료했습니다.

377 알림 목록 api memberid

---

src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java

> #371 
- 알림 확인 후 새로운 알림 상태 변경을 처리했습니다.

380 알림 확인 후 새로운 알림 상태 변경

---

src/main/java/com/codenear/butterfly/consent/application/ConsentFacade.java
src/main/java/com/codenear/butterfly/consent/application/ConsentService.java
src/main/java/com/codenear/butterfly/consent/application/ConsentUpdateService.java
src/main/java/com/codenear/butterfly/consent/infrastructure/ConsentDataAccess.java
src/main/java/com/codenear/butterfly/consent/infrastructure/ConsentRepository.java
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/notify/fcm/application/FCMFacade.java
src/main/java/com/codenear/butterfly/notify/fcm/application/FCMMessageService.java
src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java

> #371 
- 알림 목록 기능 구현과 FCM 비즈니스도 함께 연결했습니다.

379 알림 목록 추가 기능

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmResponse.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/dto/AlarmsResponse.java
src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmController.java
src/main/java/com/codenear/butterfly/notify/alarm/presentation/AlarmControllerSwagger.java

> #371 
- 알림 목록 반환 API Swagger 명세서 정의

383 알림 목록 반환 api swagger 문서화

---

src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/domain/dto/MemberInfoDTO.java
src/main/java/com/codenear/butterfly/notify/alarm/infrastructure/AlarmRepository.java

> #371 
- 유저 반환 정보에 새로운 정보 있음을 알려주는 정보 추가했습니다.

384 유저 정보에 새로운 알림 표시

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Favorite.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductInventoryRepository.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductRepository.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java

> #387 
- 상품 도메인을 리팩토링 하였습니다.
- 유동적으로 변하는 상품 데이터들에 추상 클래스를 적용하여 분리하였습니다.
- 재고수량, 현재 구매 인원, 최대 구매 인원을 분리하였습니다.

387 refactor 상품 도메인 리팩토링

---

src/main/java/com/codenear/butterfly/product/util/ProductMapper.java

> #389 
- 상품 목록 조회 API 호출시 상품 할인률이 추가할인률을 적용하도록 수정하였습니다.

refactor(ProductMapper): 상품 할인률 반환 시 추가할인률 적용

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/presentation/AdminProductsController.java
src/main/resources/templates/admin/products/product-edit.html

> #391 
- 관리자 페이지 추가할인 구간 삭제 시 오류 해결
- Ajax 요청을 통해 삭제 버튼 클릭 시 즉시 삭제되게 수정하였습니다.

391 fix 관리자 페이지 추가할인 구간 수정 오류

---

src/main/java/com/codenear/butterfly/product/domain/Keyword.java

> #393 
- 동일 키워드를 여러 상품에 키워드로 등록하기 위해 키워드 중복을 허용한다.

refactor(Keyword): 상품 추가 시 키워드 중복 허용

---

src/main/java/com/codenear/butterfly/product/domain/Option.java
src/main/java/com/codenear/butterfly/s3/application/S3Service.java
src/main/java/com/codenear/butterfly/s3/config/S3Config.java

> #395
- SQL 예약어 에러 발생 해결
- 환경 변수 이름 일관성 고려 변경 및 Bukkit Name 도 환경 변수 관리로 변경
* 환경 변수 이름 변경 점은 카카오톡으로 안내해드리겠습니다. (빠른 시일내에 Spring Cloud Config 형태로 변경 예정)

395 fix sql 예약어 option 에러

---

src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
src/main/java/com/codenear/butterfly/member/presentation/swagger/CredentialControllerSwagger.java

> #397
- 아이디/비밀번호 찾기 Swagger 문서 수정

397 feat 아이디 비밀번호 찾기

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductUpdateRequest.java
src/main/java/com/codenear/butterfly/product/application/FavoriteService.java
src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
src/main/java/com/codenear/butterfly/product/domain/dto/OptionDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html

#407 
- 신청 게이지 반환 (Float)
- 배송 정보 추가
- 상품 설명 이미지 추가
- 상품 코드 리팩토링
- 카카오페이 결제페이지 리다이렉트 오류 수정

407 feat 컬럼 추가 신청 현황 게이지 배송 정보 상품 설명 이미지 및 리팩토링

---

src/main/java/com/codenear/butterfly/member/domain/dto/ResetPasswordRequestDTO.java
src/main/java/com/codenear/butterfly/member/domain/dto/VerifyFindPasswordRequestDTO.java
src/test/java/com/codenear/butterfly/certify/application/CertifyServiceTest.java
src/test/java/com/codenear/butterfly/member/application/CredentialServiceTests.java

#406 
- CertifyServiceTest : 핸드폰 인증 예시로 수정
- CredentialServiceTest : DTO 파라미터 변경된 순서에 맞게 수정

Test : CertifyServiceTest,CredentialServiceTest 수정

---

.gitignore
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/Alarm.java
src/test/java/com/codenear/butterfly/geocoding/application/GeocodingClientTest.java
src/test/java/com/codenear/butterfly/geocoding/application/GeocodingServiceTest.java
src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java

- 테스트코드에서 alarm builder사용 오류 수정
- test코드 전용 properties 생성 및 ignore

[Fix] 테스트코드 오류 수정

---

build.gradle
src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/global/config/RabbitMQConfig.java
src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/rabbitmq/InventoryDecreaseMessageDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/rabbitmq/InventoryIncreaseMessageDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQProducer.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java

#416 
- 재고확인 순서 변경 ( 결제는 완료되었지만 재고는 차감되지 않는 오류 수정 )
-  approve -> ready
- rabbitMQ 추가
- redis + rabbitMQ로 재고 동시성 제어 (기능 추가)
- redis - 싱글 스레드로 재고 동시성 제어
- rabbitMQ - 순차처리로 DB 동시성 제어
- 상품 수정 로직 메서드 분리 (리팩토링)
- IOS 결제 완료 redirect 변경
- 결제 시 포인트 차감 안되는 오류 수정
- 테스트코드

416 fix 상품 재고 오류 수정

---

src/main/java/com/codenear/butterfly/global/config/RedisConfig.java

#421 
- Redis 비밀번호 설정 추가
- 게이지 수정
- 구간 할인율 설정
- 최대 구매 개수 이상의 물품 구매 시 할인율 차액 포인트백

refactor(RedisConfig): redis 비밀번호 설정

---

src/main/java/com/codenear/butterfly/certify/application/CertifyService.java
src/main/java/com/codenear/butterfly/certify/domain/CertifyType.java
src/main/java/com/codenear/butterfly/member/application/PhoneRegistrationService.java

> ex) #이슈번호, #이슈번호
- 핸드폰 인증 오류 수정
- 할 일을 적어주세요

Fix : 핸드폰 인증 오류 수정

---

src/main/java/com/codenear/butterfly/s3/application/S3Service.java

fix(S3Service): FileUrl 수정

---

src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/KakaoPayRedisField.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java
src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayControllerSwagger.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRedisExpiredKeyListener.java

#427 
- 사용자 주문 재고 관리 추가
- 예약된 재고에 대해서 TTL 만료 시 재고 반환
- 상품 이미지 오류 수정

427 fix 재고 예약 오류 수정

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html

#425 
- 구간할인율 적용
- 최대 구매 개수 증가 및 감소 로직 구현
- 다음 적용될 할인율 계산
- Redis에서 재고 잡는 부분 생각해서 변경하기
- 포인트백

425 feat 구간할인율 및 게이지 유동적 변경

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQProducer.java
src/main/java/com/codenear/butterfly/point/domain/Point.java

#436 
- 상태가 배송 완료로 변경 될 때, 현재 할인가에서 구매 당시 할인가에 대한 차액 포인트백
- redis TTL 적용 안되는 오류 수정
- point class builder 수정
- rabbitmq 메세지 처리 실패 시 다시 큐에 삽입하여 재처리
- 포인트 사용 시 차감 안되는 오류 수정

436 feat 포인트백 구현

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/KakaoPayRedisField.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/BasePaymentRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/request/DeliveryPaymentRequestDTO.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQConsumer.java
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPayRabbitMQProducer.java
src/main/java/com/codenear/butterfly/point/domain/Point.java

#439 
- 배달 주문 시 날짜 저장 안되는 오류 수정
- 포인트 사용 시 포인트 차감 안되는 오류 수정
- 주문 취소 시 사용한 포인트 반환
- 예약 재고 중복 오류 수정

439 fix 포인트 사용 시 차감되지 않는 오류 수정

---

src/main/java/com/codenear/butterfly/promotion/application/PointPromotionService.java
src/main/java/com/codenear/butterfly/promotion/application/PromotionDataAccess.java
src/main/java/com/codenear/butterfly/promotion/domain/PointPromotion.java

> #435 
- [pointPromotion cache 비활성화]

435 refactor 핸드폰인증

---

src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java
src/test/java/com/codenear/butterfly/promotion/application/PointPromotionServiceTest.java

Refactor : 핸드폰 인증 후 캐시 업데이트

---

src/main/java/com/codenear/butterfly/global/config/SecurityConfig.java
src/main/java/com/codenear/butterfly/global/config/SwaggerConfig.java
src/main/java/com/codenear/butterfly/global/property/SecurityProperties.java

#455 
- swagger servers https로 변경
- CORS AllowedOrigins 서버도메인으로 변경
- 프로필 이미지 변경 오류 수정

455 feat swagger https 추가

---

.gitignore
src/main/java/com/codenear/butterfly/kakaoPay/util/KakaoPaymentUtil.java

#460 
- custom_url 변경
- 동의서 페이지 ignore
- 상품 이미지 2개 이상으로 변경

460 refactor 결제 이후 페이지 홈으로 이동

---

src/main/java/com/codenear/butterfly/member/domain/dto/MemberDTO.java
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/notify/fcm/application/FCMTokenService.java
src/main/java/com/codenear/butterfly/notify/fcm/domain/FCM.java
src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FCMRepository.java
src/test/java/com/codenear/butterfly/notify/fcm/application/FCMTokenServiceTest.java

> #458 
- 재로그인 시 FCM 중복 생성 문제 해결

Refacotr : FCM토큰 재로그인 시 새 중복생성 방지

---

src/main/java/com/codenear/butterfly/member/domain/dto/MemberDTO.java
src/main/java/com/codenear/butterfly/notify/fcm/application/FCMTokenService.java

> #458 
- FCM 토큰 업데이트 시 save적용

Refactor : FCM 토큰 업데이트 시 save적용

---

src/test/java/com/codenear/butterfly/notify/fcm/application/FCMTokenServiceTest.java

> #458 
- FCM존재 시 save검증 로직 삭제

Test : FCM존재 시 save검증 로직 삭제

---

src/main/java/com/codenear/butterfly/notify/fcm/application/FCMTokenService.java
src/test/java/com/codenear/butterfly/notify/fcm/application/FCMTokenServiceTest.java

> #466 
- 같은 토큰이라도 다른 계정으로 로그인할 경우 새 fcm토큰 생성

Refactor : 다른 계정일 경우 fcm토큰 새로 추가

---

src/main/java/com/codenear/butterfly/kakaoPay/presentation/singlepay/SinglePayController.java

#468 
- success, cancel, fail 이후 리다이렉트 제거 취소

revert(SinglePayController): 결제 이후 리다이렉트 제거 취소

---

src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java

#471 
- 재고예약 TTL 시간 변경
- 15분 -> 5분 (15분으로 설정 했을 때, 재고는 많이 남아있지만 재고부족 현상이기에 반환시간을 5분으로 설정)
- 간헐적 결제성공 수정

471 refactor 재고 예약 시간 변경

---

src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/Amount.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/OrderDetails.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/SinglePayment.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ApproveFreePaymentHandler.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ApproveHandler.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/ApprovePaymentHandler.java

#473 
- 주문가격에 따른 필요정보 handling
- 주문 가격이 0원일 때 처리 로직 추가
- KakaoPay에 api보내지 않고 서버에서 바로 처리
- 결제 성공 로직 리팩토링

473 feat 결제금액 0원일 때 처리

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/admin/order/presentation/AdminOrderDetailsController.java
src/main/java/com/codenear/butterfly/notify/NotifyMessage.java

Feat : 배송완료알림, 주문취소알림

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java

> #477 
- 주문 취소 알림 동작 수정 (관리자 -> 어플 내 주문 취소)

Refactor : 앱에서 주문 취소 시 주문 취소 알림 보내도록 수정

---

src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java

Refactor : 결제취소 변경 로직에 따른 알림 코드 이동

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/kakaoPay/application/CancelPaymentService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/dto/kakao/handler/CancelPaymentHandler.java

#483 
- 포인트백 계산 수정
- 카카오페이 결제건에 대한 배송취소 오류 수정

483 fix 포인트백 안오는 오류 수정

---

src/main/java/com/codenear/butterfly/ButterflyApplication.java
src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/KakaoPaymentRedisRepository.java
src/main/java/com/codenear/butterfly/kakaoPay/util/InventorySyncScheduler.java

#485 
- 상품 변경 시 redis재고 재세팅
- 매일 새벽 4시 재고 동기화 스케줄러
- 포인트백 발생 시 알림 발송

485 feat 기존 상품 재고 변경 시 redis 재고 동기화

---

src/main/java/com/codenear/butterfly/kakaoPay/application/SinglePaymentService.java
src/main/java/com/codenear/butterfly/notify/NotifyMessage.java

487 feat 0원 결제 완료 시 결제 완료 알림

---

src/main/java/com/codenear/butterfly/consent/domain/ConsentType.java
src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java
src/main/java/com/codenear/butterfly/notify/NotifyMessage.java
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java

> ex) #이슈번호, #이슈번호
- 알림 기능 별 분리

Refactor : 알림 로직 기능 별 분리

---

src/test/java/com/codenear/butterfly/notify/application/FCMMessageServiceTest.java

> ex) #이슈번호, #이슈번호
- 동의 테스트 수정

Test : 동의 테스트 수정

---

src/main/java/com/codenear/butterfly/member/application/CredentialService.java
src/test/java/com/codenear/butterfly/member/application/CredentialServiceTest.java

Refactor : 아이디/비번 찾기 재수정

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/product/application/KeywordService.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRedisRepository.java
src/main/java/com/codenear/butterfly/product/domain/repository/KeywordRepository.java
src/main/java/com/codenear/butterfly/search/application/SearchService.java

#495 
- 키워드 삽입 및 수정 시 redis에 반영되지 않고 서버를 재시작해야 하는 이슈 변경
- 상품 생성 또는 수정 시 redis에 키워드 반영
- 공유기능

495 refactor 키워드 검색

---

src/main/java/com/codenear/butterfly/member/domain/Platform.java

feat(Platform): 애플 로그인 추가

---

build.gradle
src/main/java/com/codenear/butterfly/auth/application/AuthService.java
src/main/java/com/codenear/butterfly/auth/application/OauthService.java
src/main/java/com/codenear/butterfly/auth/application/email/EmailRegisterService.java
src/main/java/com/codenear/butterfly/global/config/RedisConfig.java
src/main/java/com/codenear/butterfly/global/util/RedisUtil.java
src/main/java/com/codenear/butterfly/member/application/PhoneRegistrationService.java
src/main/java/com/codenear/butterfly/member/domain/DeletedMember.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/member/domain/dto/MemberRegisterDTO.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/DeletedMemberRepository.java
src/main/java/com/codenear/butterfly/member/domain/repository/member/MemberRepository.java
src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java
src/main/java/com/codenear/butterfly/member/presentation/PhoneRegistrationController.java
src/main/java/com/codenear/butterfly/notify/alarm/application/AlarmService.java
src/main/java/com/codenear/butterfly/promotion/application/PointPromotionService.java
src/main/java/com/codenear/butterfly/promotion/application/PromotionDataAccess.java

> ex) #493 
- 삭제된 회원 테이블 따로 관리
- 소셜로그인 탈퇴 후 삭제 전 재로그인 시 바로 복구

493 refactor 회원탈퇴

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/admin/order/presentation/AdminOrderDetailsController.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java
src/main/resources/templates/admin/order/order-details.html

> #507 
- 주문 상태 별 필터링 기능 구현
- 필터링 상태에서 상태 변경 시 페이지 유지

Feat : 주문상태필터링

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/admin/order/presentation/AdminOrderDetailsController.java
src/main/java/com/codenear/butterfly/global/exception/ErrorCode.java
src/main/resources/templates/admin/order/order-details.html

Feat : 일괄배송완료

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/kakaoPay/domain/repository/OrderDetailsRepository.java
src/main/java/com/codenear/butterfly/point/domain/PointRepository.java
src/main/java/com/codenear/butterfly/product/domain/repository/ProductInventoryRepository.java
src/test/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsServiceTest.java

> #510 
- 일괄배송완료 리팩토링
- 상품 정보들 한 번에 조회
- 주문 별 포인트 계산
- 회원 별 포인트 한 번에 업데이트
- 한 번에 알림 발송
- 테스트 코드

Refactor :  일괄배송 배치처리

---

src/main/java/com/codenear/butterfly/product/application/ProductViewService.java
src/main/java/com/codenear/butterfly/product/presentation/ProductController.java
src/main/java/com/codenear/butterfly/search/application/SearchService.java

#512 
- 상품, 상품 검색 api 비회원 인가
- 결제수단 추가 (Toss)

512 refactor 비회원 접근

---

src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/domain/Grade.java

> #516 
- 주문 금액 별 회원 등급 업데이트 (Mysql 이벤트 스케줄러)

Feat : 주문금액 별 회원 등급

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/member/domain/Member.java
src/main/java/com/codenear/butterfly/notify/alarm/domain/Restock.java
src/main/java/com/codenear/butterfly/notify/alarm/presentation/RestockControllerSwagger.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/test/java/com/codenear/butterfly/notify/alarm/application/RestockServiceTest.java

#494 
- 재입고 알림 발송 이후 재신청 하지 않아도 알림 재발송 되는 오류 수정
- 카카오톡 배달 동시 알림 서비스

Fix: 재입고 알림 오류 수정

---

src/main/resources/templates/admin/order/order-details.html
src/main/resources/templates/fragments/sidebar.html

521 fix admin 페이지 오류 수정

---

src/main/java/com/codenear/butterfly/admin/products/application/AdminProductService.java
src/main/java/com/codenear/butterfly/admin/products/dto/ProductCreateRequest.java
src/main/java/com/codenear/butterfly/product/domain/Product.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
src/main/resources/templates/admin/products/product-create.html
src/main/resources/templates/admin/products/product-edit.html

#525 
- 상품 추가 페이지 구간 할인율 설정
- 중량과 소비기한 표시 안되는 오류 수정

525 refactor 상품 추가 시 구간 할인율 설정

---

.gitignore
src/main/java/com/codenear/butterfly/home/presentation/HomeController.java
src/main/resources/templates/home.html

527 feat 웹 홈 페이지

---

src/main/java/com/codenear/butterfly/member/infrastructure/MemberDataAccess.java

534 fix 회원 기능 오류

---

src/main/java/com/codenear/butterfly/payment/tossPay/application/TossPaymentServiceImpl.java
src/main/java/com/codenear/butterfly/payment/tossPay/domain/dto/ReadyResponseDTO.java

#536 
- ready response에 memberId 추가

feat(ReadyResponseDTO): toss ready response에 memberId 추가

---

src/main/java/com/codenear/butterfly/notify/fcm/application/FCMMessageService.java
src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FCMRepository.java
src/main/java/com/codenear/butterfly/notify/fcm/infrastructure/FirebaseMessagingClient.java
src/main/resources/templates/admin/order/order-details.html

#541 
- FCM토큰 유효성 검사
- 유효하지 않은 FCM 토큰 삭제
- 배송 준비 중 -> 배송 중 일괄처리

541 fix 배송 완료 일괄처리 에러

---

build.gradle
src/main/java/com/codenear/butterfly/global/application/DebeziumListener.java
src/main/java/com/codenear/butterfly/global/config/DebeziumConfig.java
src/main/java/com/codenear/butterfly/global/dto/DebeziumChangeEventDTO.java
src/main/java/com/codenear/butterfly/member/application/MemberService.java
src/main/java/com/codenear/butterfly/member/util/MemberDebeziumEventListener.java

#555 
- Debezium 의존성
- Debezium 환경 설정
- Debezium 이벤트 변경 리스너
- 멤버 캐시 삭제 메서드
- Member 테이블에 대한 이벤스 수신 리스너
- 기본 배송지에서 가장 가까운 스팟 계산

555 feat 사용자 grade 변경 시 캐시 업데이트

---

src/main/java/com/codenear/butterfly/payment/util/RabbitMQConsumer.java
src/main/java/com/codenear/butterfly/product/domain/ProductInventory.java
src/main/java/com/codenear/butterfly/product/domain/dto/DiscountRateDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductDetailDTO.java
src/main/java/com/codenear/butterfly/product/domain/dto/ProductViewDTO.java
src/main/java/com/codenear/butterfly/product/util/ProductMapper.java

#562 
- 사용하지 않는 변수 제거
- 할인율 구간 별 최소 신청인원, 최대 신청인원, 총 할인율 반환 (discountRateInfo)

562 feat 구간 할인율 반환

---

src/main/java/com/codenear/butterfly/admin/order/application/AdminOrderDetailsService.java
src/main/java/com/codenear/butterfly/admin/order/presentation/AdminOrderDetailsController.java
src/main/java/com/codenear/butterfly/payment/domain/repository/OrderDetailsRepository.java
src/main/resources/templates/admin/order/order-details.html

#576 
- 주문 내역에 픽업/배송에 따른 필터 추가
- 네이버 클라우드 (전화번호 인증) 확인

576 feat 픽업배달 관련 진행상태 필터 추가

---

src/main/java/com/codenear/butterfly/payment/application/PaymentService.java

#578 
- 결제 성공 프로세스 내에 결제 완료 알림 전송 추가
- 지역신청 AP

feat(PaymentService): 결제 완료 시 알림 전송
